In [88]:
l = [123, 21, 432, -21]

In [89]:
l

[123, 21, 432, -21]

In [90]:
#. In Phyton c'è l'array che ha diverso dalle liste per le sue prorpietà e funzioni 
#. 2 tipi di Array quello nel Core e quello nel package Numpy

In [91]:
import numpy as np

In [92]:
a = np.array(l) # Creare un ARRAY array()converte una lista in un array
a

array([123,  21, 432, -21])

In [93]:
w = np.array([12,1,-1,True,'q'])
w

array(['12', '1', '-1', 'True', 'q'], dtype='<U21')

In [96]:
print(w)

['12' '1' '-1' 'True' 'q']


In [97]:
#BENEFICI DEGLI ARRAY con nomearray.TAB vedi le funzioni grazie al package numpy
l.pop()

-21

In [98]:
#BENEFICI DEGLI ARRAY con nomearray.TAB vedi le funzioni grazie al package numpy
a.mean()

138.75

In [99]:
#CONCETTO DI SLICING DEGLI ARRAY
# 
a

array([123,  21, 432, -21])

In [112]:
a[2:4] # QUANDO RICHIAMIAMO DA UN ARRAY come es. dal 2 al 4 senza includerlo non ritorna una copia, bensi 
       # come in una lista, RITORNA un RIFERIMENTO

array([11, 11])

In [103]:
b = a[2:4] # impostiamo che b prende come riferimento all'indice 2 a elem 4 non includendolo

In [104]:
b

array([432, -21])

In [105]:
b[:] = 11 #prendi tuttto b e sostituiscolo con 11

In [107]:
b

array([11, 11])

In [109]:
a # vediamo che il riferimento di a è stato sovrascritto

array([123,  21,  11,  11])

In [110]:
#Per creare copia di n array
c = a.copy()
c

array([123,  21,  11,  11])

In [111]:
a

array([123,  21,  11,  11])